[package]
name = "ctl-task-client"
version.workspace = true
edition.workspace = true

[dependencies]
ctl-component-info = { workspace = true, features = ["executable"] }
ctl-task-ipc.workspace = true
ctl-task-proto.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true

[dev-dependencies]
serde_json.workspace = true
