[package]
name = "ctmux-client"
version.workspace = true
edition.workspace = true

[dependencies]
ctl-component-info.workspace = true
avt.workspace = true
crossterm.workspace = true
dirs.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
uuid.workspace = true
ctmux-proto.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
