[package]
name = "ctl-core"
version.workspace = true
edition.workspace = true

[dependencies]
component-info.workspace = true
dirs.workspace = true
glob.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
uuid.workspace = true
ctl-proto.workspace = true
ctld-ipc.workspace = true
rmux-ipc.workspace = true
task-client.workspace = true
task-ipc.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
