[package]
name = "ctl-core"
version.workspace = true
edition.workspace = true

[dependencies]
ctl-proto.workspace = true
rmux-ipc.workspace = true
task-client.workspace = true
task-ipc.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
serde_json.workspace = true
uuid.workspace = true

[lints]
workspace = true
