[package]
name = "rmuxd"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
avt.workspace = true
portable-pty.workspace = true
rmux-core.workspace = true
rmux-ipc.workspace = true
rmux-proto.workspace = true
rustix.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[lints]
workspace = true
