[package]
name = "taskd"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
dirs.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
task-proto.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
task-proto.workspace = true
tokio.workspace = true
uuid.workspace = true

[lints]
workspace = true
