[package]
name = "rmux"
version.workspace = true
edition.workspace = true

[lib]
name = "rmux_cli"
path = "src/lib.rs"

[dependencies]
serde_json.workspace = true
clap.workspace = true
rmux-client.workspace = true
rmux-ipc.workspace = true
rmux-proto.workspace = true
thiserror.workspace = true
tokio.workspace = true

rmux-tui = { path = "../../apps/tui" }

[dev-dependencies]
rmuxd.workspace = true
uuid.workspace = true

[lints]
workspace = true
