[package]
name = "rmux-client"
version.workspace = true
edition.workspace = true

[dependencies]
crossterm.workspace = true
dirs.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
uuid.workspace = true
rmux-proto.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lints]
workspace = true
