[package]
name = "ctl-keychain-client"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
zeroize.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10.1"
security-framework = { version = "3.7", features = ["OSX_10_15"] }
security-framework-sys = { version = "2.17", features = ["OSX_10_15"] }

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = "warn"
pedantic = "warn"
